version: '3.9'
services:
  mail-delivery-service:
    container_name: mail-delivery-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    environment:
      - KAFKA_SERVER=http://kafka-server:9092/
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  zookeeper:
      image: docker.io/bitnami/zookeeper:3-debian-10
      ports:
        - '2181:2181'
      volumes:
        - 'zookeeper_data:/bitnami'
      environment:
        ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka-server:
      image: docker.io/bitnami/kafka:2-debian-10
      restart: "no"
      ports:
        - "9092:9092"
      volumes:
        - 'kafka_data:/bitnami'
      environment:
        KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
        KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
        KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
        KAFKA_RESTART_ATTEMPTS: "10"
        KAFKA_RESTART_DELAY: "5"
        ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
        KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
        ALLOW_PLAINTEXT_LISTENER: "yes"

volumes:
    zookeeper_data:
      driver: local
    kafka_data:
      driver: local

networks:
  default:
    external:
      name: mail-delivery-network